CREATE TABLE audit (
  id         BIGINT       NOT NULL AUTO_INCREMENT,
  name       VARCHAR(255) NULL,
  created_at TIMESTAMP(6)          DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6)          DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id)
);
